### ISSUE TITLE
`#[doc(hidden)]` re-exports of non-`#[doc(hidden)]` items considered public API

### ISSUE THREAD

**Issue by SabrinaJewson** [davidpdrsn/cargo-public-api-crates#6]
<details><summary>Old issue description (incorrect)</summary>
Currently, for the code:

```rs
#[doc(hidden)]
pub use some_crate;
```

`some_crate` is considered to be public API. However, it could just be used internally for a macro, and thus this diagnosis is incorrect. Note that in the general case this is hard:

```rs
#[macro_export]
macro_rules! evil {
    () => { $crate::some_crate::SomeUnitStruct };
}
#[doc(hidden)]
pub use some_crate;
```

And rarely, `#[doc(hidden)]` is used for items that are in the public API (e.g. I believe that `hyper::http` is public API, despite beïng `#[doc(hidden)]`).

So I suggest something like:

```toml
[package.metadata.cargo-public-api-crates]
allowed = ["…"]
allowed-in-hidden = ["some_crate"]
```

or:

```toml
[package.metadata.cargo-public-api-crates]
allowed = [{ name = "some_crate", doc_hidden_only = true }]
```
</details>

In the following code:

```rs
#[doc(hidden)]
pub use m::some_crate;
mod m {
    pub use some_crate;
}
```

`some_crate` is considered a public dependency. This is incorrect. It can be worked around by using `#[doc(hidden)]` in more places:

```rs
#[doc(hidden)]
pub use m::some_crate;
mod m {
    #[doc(hidden)]
    pub use some_crate;
}
```
